export const artists = [
  {
    id: "nova-saints",
    initials: "BT",
    name: "Black-Tokyo",
    genre: "Alternative / electronic soul",
    city: "Austin, TX",
    tagline: "Melodic pressure, analog haze, and after-hours atmosphere.",
    bio: "Black-Tokyo moves between electronic textures, vocal fragments, and widescreen arrangements built for late-night listening.",
    accent: "135deg, #ff8a5b 0%, #ff4d6d 50%, #ffcc70 100%",
    heroStat: "2.1M monthly listeners across platforms",
    stats: [
      { value: "9", label: "Releases" },
      { value: "2.1M", label: "Monthly listeners" },
      { value: "5", label: "Platforms" },
    ],
    handles: {
      x: "@novasaints",
      instagram: "@blacktokyo",
      soundcloud: "soundcloud.com/blacktokyo",
      bandcamp: "blacktokyo.bandcamp.com",
      spotify: "Black-Tokyo",
    },
  },
  {
    id: "ivy-echo",
    initials: "ES",
    name: "Electric Synagogue",
    genre: "Experimental / psych electronics",
    city: "Austin, TX",
    tagline: "Ritual rhythms, fractured synths, and saturated motion.",
    bio: "Electric Synagogue bends psych, electronics, and underground club energy into records that feel both raw and cinematic.",
    accent: "135deg, #88d498 0%, #5bc0eb 50%, #9d4edd 100%",
    heroStat: "Featured on 38 editorial playlists this year",
    stats: [
      { value: "7", label: "Releases" },
      { value: "38", label: "Editorial playlists" },
      { value: "5", label: "Platforms" },
    ],
    handles: {
      x: "@ivyecho",
      instagram: "@electricsynagogue",
      soundcloud: "soundcloud.com/electricsynagogue",
      bandcamp: "electricsynagogue.bandcamp.com",
      spotify: "Electric Synagogue",
    },
  },
  {
    id: "funeral-disco",
    initials: "HD",
    name: "Heezy Duz",
    genre: "Lofi hip hop / beat tape",
    city: "Austin, TX",
    tagline: "Dusty loops, smoked-out drums, and no-waste beat tapes.",
    bio: "Heezy Duz builds instrumental records from texture, soul fragments, and unhurried rhythm, keeping the process raw and direct.",
    accent: "135deg, #f6bd60 0%, #f28482 45%, #3d405b 100%",
    heroStat: "Sold out 12 headline dates on the last run",
    stats: [
      { value: "11", label: "Releases" },
      { value: "12", label: "Sold out shows" },
      { value: "5", label: "Platforms" },
    ],
    handles: {
      x: "@funeraldisco",
      instagram: "@heezyduz",
      soundcloud: "soundcloud.com/heezyduz",
      bandcamp: "heezyduz.bandcamp.com",
      spotify: "Heezy Duz",
    },
  },
  {
    id: "nightwerk",
    initials: "NW",
    name: "NIGHTWERK",
    genre: "Electronic / house / UK garage",
    city: "Austin, TX",
    tagline: "Club pressure, nocturnal melodies, and warehouse pulse.",
    bio: "NIGHTWERK is the after-hours corner of the label, built on stripped percussion, low-lit synth lines, and heavy motion.",
    accent: "135deg, #59c3c3 0%, #52489c 55%, #ecb0e1 100%",
    heroStat: "New EP cycle rolling into late-night club sets",
    stats: [
      { value: "6", label: "Releases" },
      { value: "1.1k", label: "Monthly listeners" },
      { value: "5", label: "Platforms" },
    ],
    handles: {
      x: "@nightwerk",
      instagram: "@nightwerk",
      soundcloud: "soundcloud.com/nightwerk",
      bandcamp: "nightwerk.bandcamp.com",
      spotify: "NIGHTWERK",
    },
  },
];

export const releases = [
  {
    id: "afterlight",
    artistId: "nova-saints",
    title: "Afterlight",
    format: "EP",
    year: "2026",
    blurb: "Five tracks of widescreen alt-pop built for midnight drives and sunrise comedowns.",
    platforms: ["Spotify", "Bandcamp", "SoundCloud"],
    source: "Bandcamp",
  },
  {
    id: "glass-mouth",
    artistId: "ivy-echo",
    title: "Glass Mouth",
    format: "Single",
    year: "2026",
    blurb: "A slow-burn rap ballad with submerged pads, detuned keys, and a brutal last verse.",
    platforms: ["Spotify", "Instagram Reels", "SoundCloud"],
    source: "Spotify",
  },
  {
    id: "saints-of-the-aisle",
    artistId: "funeral-disco",
    title: "Sunday Tape",
    format: "LP",
    year: "2025",
    blurb: "A beat tape of dusty loops, low-slung drums, and smoked-out textures.",
    platforms: ["Spotify", "Bandcamp", "Vinyl pre-order"],
    source: "Bandcamp",
  },
  {
    id: "afterglow",
    artistId: "nightwerk",
    title: "Afterglow",
    format: "EP",
    year: "2026",
    blurb: "Six late-night cuts crossing UK garage, house pulse, and blurred neon melody.",
    platforms: ["Spotify", "Bandcamp", "SoundCloud"],
    source: "Spotify",
  },
];

export const blogPosts = [
  {
    id: "tour-diary",
    category: "Behind the scenes",
    title: "Inside the first week of the Ghost Circuit tour",
    excerpt: "Load-ins, synth failures, motel rewrites, and why the second night changed the set forever.",
    date: "April 2026",
  },
  {
    id: "producer-notes",
    category: "Studio notes",
    title: "How Black-Tokyo shaped the low-end on Afterlight",
    excerpt: "A session breakdown on bass design, vocal space, and when to leave the chorus unfinished.",
    date: "March 2026",
  },
  {
    id: "label-letter",
    category: "Journal",
    title: "Why this label is building artist pages like living archives",
    excerpt: "We want every artist hub to feel like a living home for music, visuals, writing, and conversation.",
    date: "February 2026",
  },
];

export const feedItems = [
  {
    id: "feed-1",
    artistId: "nova-saints",
    platform: "Instagram",
    source: "IG",
    type: "Studio clip",
    publishedAt: "3h ago",
    title: "Hook idea from tonight's writing camp",
    body: "Short-form studio clip teasing a chorus pass and new visual moodboard.",
  },
  {
    id: "feed-2",
    artistId: "nova-saints",
    platform: "Spotify",
    source: "SP",
    type: "Release update",
    publishedAt: "1d ago",
    title: "Afterlight added to Fresh Finds",
    body: "Editorial playlist placement pushed to both the global feed and the artist hub.",
  },
  {
    id: "feed-3",
    artistId: "ivy-echo",
    platform: "X",
    source: "X",
    type: "Post",
    publishedAt: "6h ago",
    title: "New visual concept thread",
    body: "A platform post previewing lyrics, stills, and a release countdown.",
  },
  {
    id: "feed-4",
    artistId: "ivy-echo",
    platform: "SoundCloud",
    source: "SC",
    type: "Upload",
    publishedAt: "2d ago",
    title: "Glass Mouth demo cut",
    body: "Private-demo style upload promoted into the music and artist sections.",
  },
  {
    id: "feed-5",
    artistId: "funeral-disco",
    platform: "Bandcamp",
    source: "BC",
    type: "Merch drop",
    publishedAt: "4h ago",
    title: "Sunday Tape cassette run",
    body: "Short-run physical drop with handmade inserts and alternate cover art.",
  },
  {
    id: "feed-6",
    artistId: "funeral-disco",
    platform: "Instagram",
    source: "IG",
    type: "Live photo set",
    publishedAt: "1d ago",
    title: "Photos from the Mercury Room show",
    body: "Gallery post feeding the main social wall and the band page automatically.",
  },
  {
    id: "feed-7",
    artistId: "nightwerk",
    platform: "Instagram",
    source: "IG",
    type: "Release post",
    publishedAt: "8h ago",
    title: "Afterglow is out now",
    body: "Launch post pushing listeners to the new EP across streaming platforms.",
  },
  {
    id: "feed-8",
    artistId: "nightwerk",
    platform: "TikTok",
    source: "TT",
    type: "Clip",
    publishedAt: "2d ago",
    title: "Afterglow track preview",
    body: "A teaser clip from the new EP, mirrored into the artist hub automatically.",
  },
  {
    id: "feed-9",
    artistId: "nova-saints",
    platform: "Facebook",
    source: "FB",
    type: "Announcement",
    publishedAt: "1d ago",
    title: "Studio residency recap",
    body: "Photo recap and update post from the latest writing residency week.",
  },
  {
    id: "feed-10",
    artistId: "funeral-disco",
    platform: "TikTok",
    source: "TT",
    type: "Live clip",
    publishedAt: "9h ago",
    title: "Mercury Room floor video",
    body: "Short vertical clip from the headline set, shared into the artist hub and social page.",
  },
  {
    id: "feed-11",
    artistId: "ivy-echo",
    platform: "Facebook",
    source: "FB",
    type: "Post",
    publishedAt: "3d ago",
    title: "Visual diary update",
    body: "A longer-form post collecting stills, notes, and release sketches in one place.",
  },
];
